//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    
    public partial class fn_ListPhieuThu_Result2
    {
        public int PhieuThuId { get; set; }
        public string Ma_HV { get; set; }
        public string HoTen_HV { get; set; }
        public string HoTen_NV { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public int HocVienId { get; set; }
    }
}
