//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    using System.Collections.Generic;

    public partial class HocVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocVien()
        {
            this.PhieuThus = new HashSet<PhieuThu>();
        }

        public int HocVienId { get; set; }
        public string Ma_HV { get; set; }
        public string HoTen_HV { get; set; }
        public string DiaChi_HV { get; set; }
        public string Email_HV { get; set; }
        public string SDT_HV { get; set; }
        public string TrangThai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThu> PhieuThus { get; set; }
        public virtual TaiKhoanHocVien TaiKhoanHocVien { get; set; }
    }
}
