//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    using System.Collections.Generic;

    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.PhieuThus = new HashSet<PhieuThu>();
        }

        public int LopHocId { get; set; }
        public string Ma_LH { get; set; }
        public string Ten_LH { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau_LH { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc_LH { get; set; }
        public Nullable<decimal> HocPhi { get; set; }
        public Nullable<int> NhanVienId { get; set; }
        public Nullable<int> KhoaHocId { get; set; }
        public Nullable<int> LevelsId { get; set; }
        public Nullable<int> SoBuoiHoc { get; set; }
        public string KhungGioHoc { get; set; }
        public string TrangThai { get; set; }

        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual Level Level { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThu> PhieuThus { get; set; }
    }
}
