//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien_audits
    {
        public int Change_id { get; set; }
        public string Ma_NV { get; set; }
        public string HoTen_NV { get; set; }
        public string ChucVu { get; set; }
        public string Email { get; set; }
        public string SDT_NV { get; set; }
        public string CMND_NV { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime Update_at { get; set; }
        public string Operation { get; set; }
    }
}
