//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;

    public partial class TaiKhoanHocVien
    {
        public int TaiKhoanHocVienId { get; set; }
        public int HocVienId { get; set; }
        public string Username { get; set; }
        public string TrangThai { get; set; }
        public string PassWords { get; set; }
        public Nullable<int> PhanQuyenId { get; set; }

        public virtual HocVien HocVien { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
