//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaikhoanGiaoVien
    {
        public int TaiKhoanGiaoVienId { get; set; }
        public int NhanVienId { get; set; }
        public string Username { get; set; }
        public string ChucVu { get; set; }
        public string PassWords { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> PhanQuyenId { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
