//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ListGiaoVien
    {
        public string HoTen_NV { get; set; }
        public string Ma_NV { get; set; }
        public int NhanVienId { get; set; }
    }
}
